# Generated by Django 6.0 on 2026-03-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_codigorecuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_contrasena',
            field=models.BooleanField(default=False),
        ),
    ]
