# Generated by Django 6.0 on 2026-03-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
