# Generated by Django 6.0.3 on 2026-03-11 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='mensaje',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='creada',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
