# Generated by Django 6.0.3 on 2026-03-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_options_rename_mensaje_cita_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora']},
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
