# Generated by Django 6.0.3 on 2026-03-12 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_options_cita_estado_and_more'),
        ('usuario', '0002_alter_usuario_date_joined_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
