# Generated by Django 6.0 on 2026-02-28 16:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenProducto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
