# Generated by Django 6.0 on 2026-03-08 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colores', '0006_delete_imagencolor'),
        ('imagenProducto', '0002_imagenproducto_orden_alter_imagenproducto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='colores.colorproducto'),
            preserve_default=False,
        ),
    ]
