# Generated by Django 6.0 on 2026-03-08 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0005_alter_producto_modelo_glb_alter_producto_modelo_usdz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_hex', models.CharField(max_length=7)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='productos.producto')),
            ],
        ),
    ]
