# Generated by Django 6.0 on 2026-03-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorproducto',
            old_name='producto',
            new_name='Producto',
        ),
        migrations.RemoveField(
            model_name='colorproducto',
            name='codigo_hex',
        ),
        migrations.AddField(
            model_name='colorproducto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='colores/'),
            preserve_default=False,
        ),
    ]
