# Generated by Django 6.0 on 2026-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colores', '0002_rename_producto_colorproducto_producto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorproducto',
            old_name='Producto',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='colorproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='colores/'),
        ),
    ]
