# Generated by Django 6.0 on 2026-03-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colores', '0003_rename_producto_colorproducto_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorproducto',
            name='codigo_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
