# Generated by Django 6.0 on 2026-03-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colores', '0004_colorproducto_codigo_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos_colores/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='colores.colorproducto')),
            ],
        ),
    ]
