# Generated by Django 6.0 on 2026-03-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colores', '0005_imagencolor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenColor',
        ),
    ]
