# Generated by Django 6.0.3 on 2026-03-17 15:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colores', '0006_delete_imagencolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorproducto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
