# Generated by Django 6.0 on 2026-02-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=0, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
