# Generated by Django 6.0 on 2026-02-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='modelo_glb',
            field=models.FileField(blank=True, null=True, upload_to='modelos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo_usdz',
            field=models.FileField(blank=True, null=True, upload_to='modelos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
