# Generated by Django 6.0 on 2026-02-28 16:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_modelo_glb_producto_modelo_usdz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo_glb',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='modelo_glb'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo_usdz',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='modelo_usdz'),
        ),
    ]
