# Generated by Django 6.0.3 on 2026-03-18 17:06

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_modelo_glb_alter_producto_modelo_usdz'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Alto en cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ancho en cm', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='material',
            field=models.CharField(blank=True, help_text='Ej: Madera de teca, cuero natural', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Peso en kg', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='profundidad',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Profundidad en cm', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='ImagenDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen_dimension')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Vista frontal, Vista superior', max_length=100, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_dimensiones', to='productos.producto')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
